image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  DOCKER_TLS_CERTDIR: ""
  project: "Project"

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project/src/$project"
  script:
    - "cd $build_path"
    - "dotnet build"

test:
  stage: test
  variables:
    test_path: "$project.Tests"
  script:
    - "cd $test_path"
    - "dotnet test"
